


spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    properties:
      hibernate.show-sql: true
      hibernate.format-sql: true
      hibernate.use-sql-comments: true
    show-sql: true